# Generated by Django 5.2.16 on 2026-07-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='emoji',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', '💼 Work'), ('Learning', '📚 Learning'), ('Health', '💪 Health'), ('Personal', '📝 Personal')], default='Personal', max_length=20),
        ),
    ]
